apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: database-monitoring
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 31000
  selector:
    app: two-tier-app
  type: NodePort