apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: database-monitoring
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql 
  type: ClusterIP